prefixes = [
    "organic ",
    "natural ",
    "dried ",
    "sundried ",
    "roasted ",
    "shredded ",
    "fresh ",
    "diced ",
    "fried ",
    "chargrilled ",
    "dehydrated ",
    "rehydrated ",
    "blanched",
    "unpeeled ",
    "peeled",
    "powdered ",
    "ground ",
    "caramelized ",
    "caramelised ",
    "condensed ",
    "evaporated ",
    "distilled ",
    "clarified ",
    "sparkling ",
    "carbonated ",
    "minced ",
    "crushed ",
    "freeze dried ",
    "freeze-dried ",
    "sun dried ",
    "sun-dried ",
    "fermented ",
    "concentrated ",
    "semi sweet ",
    "semi-sweet ",
    "salted ",
    "unsalted ",
    "spicy ",
    "unsweetened ",
    "sweetened ",
    "sweet ",
    "hot ",
    "dry ",
    "flavored ",
    "premium ",
    "select ",
    "pure ",
    "refined ",
    "unrefined ",
    "pasteurized ",
    "unpasteurized ",
    "whole ",
    "extra virgin ",
    "cold-pressed ",
    "cold pressed ",
    "single-origin ",
    "single origin ",
    "unbleached ",
    "enriched ",
    "expeller ",
    "pressed ",
    "extractives ",
    "cooked ",
    "precooked ",
    "savory ",
    "dehulled ",
    "hulled ",
    "and ",
    "& ",
    "grade a",
    "of ",
    "partially ",
    "hydrogenated ",
    "artificial ",
    "flavor "
]

suffixes = [
    " puree",
    " pepper",
    " paste",
    " powder",
    " extract",
    " extractive",
    " concentrate",
    " essence",
    " flakes",
    " granules",
    " flavoring",
    " flavor",
    " dip",
    " crumbs",
    " cubes",
    " chunks",
    " coated",
    " broth",
    " stock",
    " pulp",
    " piece",
    " with pulp",
    " with micro pulp",
    " base",
    " blend",
    " broth",
    " from concentrate"
]